"""Slide deck generation (.pptx).

Generates a slide deck summarizing the study. If ``python-pptx`` is
installed (it is a core dependency) a real .pptx file is
produced; otherwise a Markdown outline that can be imported into any slide
tool is written as a fallback. This keeps the report phase functional in
minimal environments while opening the door to richer output when the
extra is installed.
"""

from __future__ import annotations

from fastmdxplora.utils.logging import get_logger
from pathlib import Path
from typing import TYPE_CHECKING

from fastmdxplora.report.context import (
    PhaseContext,
    _system_label,
    load_phase_context,
)

if TYPE_CHECKING:
    from fastmdxplora.orchestrator import FastMDXplora

logger = get_logger("report.slides")


def _slide_text(value: object, *, limit: int = 500) -> str:
    text = str(value)
    text = " ".join(text.replace("\t", " ").splitlines())
    text = " ".join(text.split())
    if len(text) > limit:
        return text[: limit - 1].rstrip() + "..."
    return text


def _workflow_lines(phase_context: PhaseContext) -> list[str]:
    if phase_context.is_full_pipeline:
        return [
            "Full FastMDXplora workflow: setup, simulation, analysis, and report.",
        ]
    if phase_context.is_analysis_from_existing_trajectory:
        return [
            "Analysis/report workflow from an existing trajectory.",
            "Setup and simulation were not run in this workflow.",
        ]
    lines = ["Recorded workflow phases:"]
    if phase_context.setup_present:
        lines.append("Setup phase recorded.")
    if phase_context.simulation_present:
        lines.append("Simulation phase recorded.")
    if phase_context.analysis_present:
        lines.append("Analysis phase recorded.")
    if phase_context.report_present:
        lines.append("Report phase recorded.")
    return lines


def _figure_title(analysis: str, fig_path: Path) -> tuple[str, str]:
    friendly = {
        "rmsd": "RMSD over frames",
        "rmsf": "RMSF by residue",
        "rg": "Radius of gyration",
        "hbonds": "Hydrogen bonds",
        "sasa": "SASA",
        "ss": "Secondary structure",
        "dihedrals": "Ramachandran / dihedrals",
        "qvalue": "Fraction of native contacts",
        "cluster": "Clustering",
        "dimred": "PCA / dimensionality reduction",
    }
    title = friendly.get(analysis, analysis.replace("_", " ").title())
    subtitle = ""
    if fig_path.stem != analysis:
        suffix = fig_path.stem.replace(f"{analysis}_", "", 1)
        if suffix.endswith("_counts") or suffix == "counts":
            title = "Cluster populations"
            method = suffix.replace("_counts", "")
            subtitle = f"method: {method.replace('_', ' ')}" if method else ""
        elif suffix == "hierarchical_dendrogram":
            title = "Hierarchical clustering dendrogram"
        else:
            subtitle = f"method: {suffix.replace('_', ' ')}"
    return title, subtitle


def _outline_markdown(orchestrator: "FastMDXplora", title: str) -> str:
    from fastmdxplora import __citation__, __version__

    phase_context = load_phase_context(orchestrator.output_dir)
    section_no = 1
    lines = [
        f"# {_slide_text(title)}",
        "",
        f"## {section_no}. Overview",
        f"- System: `{_slide_text(_system_label(orchestrator.system))}`",
        f"- Generated by FastMDXplora v{__version__}",
    ]
    lines.extend(f"- {_slide_text(line)}" for line in _workflow_lines(phase_context))

    # The same content as the deck. This outline used to say "See
    # setup_parameters.json" for three of its five sections, which is a
    # pointer rather than an outline, and it described a deck that had long
    # since stopped saying that.
    root = orchestrator.output_dir

    # `list.extend` returns None, so "extend(...) or append(fallback)" runs the
    # fallback every time: the outline carried the bullets and then told the
    # reader to go and look at the JSON anyway.
    for present, heading, bullets, fallback in (
        (phase_context.setup_present, "How the system was built",
         _setup_bullets(root), "setup/setup_parameters.json"),
        (phase_context.simulation_present, "How it was simulated",
         _simulation_bullets(root), "simulation/simulation_parameters.json"),
    ):
        if not present:
            continue
        section_no += 1
        lines.extend(["", f"## {section_no}. {heading}"])
        if bullets:
            lines.extend(f"- {b}" for b in bullets)
        else:
            lines.append(f"- See `{fallback}`")

    if phase_context.analysis_present:
        section_no += 1
        summary_figure = orchestrator.output_dir / "report" / "analysis_summary.png"
        lines.extend(
            [
                "",
                f"## {section_no}. Analysis",
                "- See `analysis/analysis_manifest.json`",
                "- Per-analysis options in `analysis/<analysis>/options.json`",
            ]
        )
        if summary_figure.is_file():
            lines.append("- Summary figure: `report/analysis_summary.png`")
        region_figure = orchestrator.output_dir / "report" / "region_highlight_summary.png"
        if region_figure.is_file():
            lines.append("- Region highlights: `report/region_highlight_summary.png`")

    findings = _findings_bullets(orchestrator.output_dir)
    if findings:
        section_no += 1
        lines.extend(["", f"## {section_no}. What the run supports"])
        lines.extend(f"- {b}" for b in findings if b)

    section_no += 1
    lines.extend(["", f"## {section_no}. Citation", f"- {__citation__}", ""])
    return "\n".join(lines)


def _build_pptx(orchestrator: "FastMDXplora", title: str, out_path: Path) -> None:
    """Write a .pptx using python-pptx (called only if importable)."""
    from pptx import Presentation
    from pptx.util import Inches, Pt

    from fastmdxplora import __citation__, __version__

    prs = Presentation()
    blank = prs.slide_layouts[5]  # Title only
    title_layout = prs.slide_layouts[0]  # Title slide

    # 16:9. python-pptx defaults to 10 x 7.5 inches, which is 4:3 and shows on
    # a modern projector with a black band down each side. The figures are
    # placed relative to these, so widening the slide widens them too.
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)
    slide_w = prs.slide_width
    slide_h = prs.slide_height

    def _set_title_font(slide, size: int = 24) -> None:
        title_shape = slide.shapes.title
        if title_shape is None or not title_shape.has_text_frame:
            return
        for paragraph in title_shape.text_frame.paragraphs:
            for run in paragraph.runs:
                run.font.size = Pt(size)
            paragraph.font.size = Pt(size)

    # Title slide
    s = prs.slides.add_slide(title_layout)
    s.shapes.title.text = _slide_text(title)
    s.placeholders[1].text = (
        f"FastMDXplora v{__version__}\n"
        f"System: {_slide_text(_system_label(orchestrator.system))}"
    )

    def _section_slide(heading: str, body_lines: list[str]) -> None:
        slide = prs.slides.add_slide(blank)
        slide.shapes.title.text = _slide_text(heading)
        _set_title_font(slide)
        textbox = slide.shapes.add_textbox(Inches(0.5), Inches(1.5), Inches(9), Inches(5))
        tf = textbox.text_frame
        tf.word_wrap = True
        for i, line in enumerate(body_lines):
            p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
            p.text = _slide_text(line, limit=700)
            p.font.size = Pt(18)

    def _image_slide(heading: str, image_path: Path, subtitle: str = "") -> None:
        """A slide that's a single titled image, centered and fit-to-slide.

        Computes a target rectangle below the title (top ~1.4 in), preserves
        the image's aspect ratio, and inserts the figure with a thin margin.
        """
        slide = prs.slides.add_slide(blank)
        slide.shapes.title.text = _slide_text(heading)
        _set_title_font(slide)

        # Optional subtitle just under the title
        if subtitle:
            sub_box = slide.shapes.add_textbox(
                Inches(0.5), Inches(1.1), slide_w - Inches(1.0), Inches(0.4)
            )
            sub_tf = sub_box.text_frame
            sub_tf.word_wrap = True
            p = sub_tf.paragraphs[0]
            p.text = _slide_text(subtitle)
            p.font.size = Pt(12)
            p.font.italic = True

        # Available region for the figure
        top = Inches(1.55)
        margin = Inches(0.3)
        avail_w = slide_w - 2 * margin
        avail_h = slide_h - top - margin

        # python-pptx will auto-size when only one dimension is given; we'd
        # rather scale ourselves to keep the figure inside the rectangle.
        from PIL import Image  # python-pptx already pulls Pillow in

        try:
            with Image.open(image_path) as im:
                img_w_px, img_h_px = im.size
            aspect = img_w_px / img_h_px
            # Fit by width first, then by height if too tall.
            target_w = avail_w
            target_h = int(avail_w / aspect)
            if target_h > avail_h:
                target_h = avail_h
                target_w = int(avail_h * aspect)
            left = (slide_w - target_w) // 2
            slide.shapes.add_picture(
                str(image_path), left, top, width=target_w, height=target_h
            )
        except Exception:  # noqa: BLE001 -- fall back to bare insert
            slide.shapes.add_picture(
                str(image_path), Inches(1.0), top, width=Inches(8.0)
            )

    project_root = orchestrator.output_dir
    phase_context = load_phase_context(project_root)

    _section_slide("Workflow", _workflow_lines(phase_context))

    # What was done, not where it was written. These slides used to read
    # "System preparation phase outputs: • /tmp/audit/setup", which is a
    # filesystem path from somebody else's machine projected onto a wall.
    if phase_context.setup_present:
        bullets = _setup_bullets(project_root)
        if bullets:
            _section_slide("How the system was built", bullets)
    if phase_context.simulation_present:
        bullets = _simulation_bullets(project_root)
        if bullets:
            _section_slide("How it was simulated", bullets)

    # Analysis: one cover slide (textual summary) + one image slide per figure
    analysis_dir = project_root / "analysis"
    manifest = _load_analysis_manifest(analysis_dir)
    plan = manifest.get("plan", [])

    if plan:
        cover_lines = [
            "Trajectory analyses performed in this session:",
        ]
        for analysis in plan:
            result = manifest.get("results", {}).get(analysis, {})
            status = result.get("status", "unknown")
            cover_lines.append(f"  • {analysis}  ({status})")
        cover_lines.append("")
        n_frames = manifest.get("n_frames")
        n_residues = manifest.get("n_residues")
        if n_frames is not None and n_residues is not None:
            cover_lines.append(
                f"Trajectory: {n_frames} frames, {n_residues} residues"
            )
        _section_slide("Analysis", cover_lines)

        summary_figure = project_root / "report" / "analysis_summary.png"
        if summary_figure.is_file():
            _image_slide("Analysis summary", summary_figure)

        region_figure = project_root / "report" / "region_highlight_summary.png"
        if region_figure.is_file():
            _image_slide("Region highlights", region_figure)

        # One image slide per produced figure, in plan order.
        for analysis in plan:
            sub_dir = analysis_dir / analysis
            if not sub_dir.is_dir():
                continue
            figures = sorted(sub_dir.glob("*.png"))
            for fig_path in figures:
                heading, subtitle = _figure_title(analysis, fig_path)
                _image_slide(heading, fig_path, subtitle=subtitle)
    else:
        _section_slide(
            "Analysis",
            [
                "Trajectory analysis outputs are in the run directory,",
                "with each analysis's options recorded beside its data.",
            ],
        )

    # Twelve figures and not one number. Every observable's mean, its
    # uncertainty and the independent samples behind it are recorded by the
    # time the deck is built, and a presentation showing only pictures leaves
    # its audience with nothing to quote.
    findings = _findings_bullets(project_root)
    if findings:
        _section_slide("What the run supports", findings)

    _section_slide(
        "Citation",
        [
            "If you use FastMDXplora in your work, please cite:",
            "",
            __citation__,
        ],
    )

    prs.save(str(out_path))


def _recorded(project_root: Path, phase: str) -> dict:
    """A phase's recorded parameters, flattened, or an empty mapping."""
    import json

    path = project_root / phase / f"{phase}_parameters.json"
    try:
        record = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    flat = dict(record)
    nested = record.get("parameters")
    if isinstance(nested, dict):
        flat.update(nested)
    resolved = record.get("resolved_forcefield")
    if isinstance(resolved, dict):
        flat.update(resolved)
    return flat


def _setup_bullets(project_root: Path) -> list[str]:
    """What the system is, in the form somebody would ask about it."""
    r = _recorded(project_root, "setup")
    if not r:
        return []

    bullets: list[str] = []
    atoms = r.get("n_atoms_solvated")
    if isinstance(atoms, int):
        bullets.append(f"{atoms:,} atoms after solvation")

    xmls = r.get("xmls")
    field = ", ".join(xmls) if isinstance(xmls, list) else r.get("forcefield")
    if field:
        water = r.get("water_model")
        bullets.append(f"Force field: {field}"
                       + (f", {water} water" if water else ""))
    if r.get("ligand") and r.get("ligand_forcefield"):
        bullets.append(f"Ligand {r.get('ligand_name')}: "
                       f"{r['ligand_forcefield']}")
    if r.get("membrane"):
        bullets.append(f"Membrane: {r['membrane']}")

    padding, shape = r.get("solvent_padding_nm"), r.get("box_shape")
    if padding and shape:
        salt = r.get("ion_concentration_M")
        bullets.append(f"Box: {shape}, {padding:g} nm padding"
                       + (f", {salt:g} M salt" if salt else ""))
    if r.get("ph") is not None:
        bullets.append(f"Protonated at pH {r['ph']:g}")
    return bullets


def _simulation_bullets(project_root: Path) -> list[str]:
    """The protocol, as a methods section would state it."""
    r = _recorded(project_root, "simulation")
    if not r:
        return []

    bullets: list[str] = []
    duration = r.get("duration_ns_actual") or r.get("duration_ns")
    if isinstance(duration, (int, float)) and duration > 0:
        length = (f"{duration * 1000:.0f} ps" if duration < 1
                  else f"{duration:.3g} ns")
        bullets.append(f"Production: {length}")

    # `pressure_bar` is what was asked for and is None when the default was
    # taken; `pressure_bar_used` is what the barostat ran at. Reading the
    # first called an NPT run at 1 bar an NVT one.
    temperature = r.get("temperature_K")
    pressure = r.get("pressure_bar_used") or r.get("pressure_bar")
    if temperature:
        bullets.append(f"{temperature:g} K"
                       + (f", {pressure:g} bar (NPT)" if pressure else " (NVT)"))
    timestep = r.get("timestep_fs")
    if timestep:
        bullets.append(f"{r.get('integrator', 'Langevin')} integrator, "
                       f"{timestep:g} fs timestep")
    if r.get("constraints"):
        bullets.append(f"Constraints: {r['constraints']}")
    if r.get("restrain"):
        bullets.append("Restraints applied during equilibration and released")
    for method in ("umbrella", "steered", "metadynamics"):
        if r.get(method):
            bullets.append(f"Enhanced sampling: {method}")
    platform = r.get("platform_used") or r.get("platform")
    if platform:
        bullets.append(f"OpenMM on {platform}")
    seed = r.get("random_seed")
    bullets.append(f"Random seed: {seed}" if seed is not None
                   else "No fixed seed; velocities differ between runs")
    return bullets


def _findings_bullets(project_root: Path) -> list[str]:
    """Each observable's mean with its honest uncertainty, and the caveats.

    Built from the same assessment the report's convergence section uses, so
    the deck and the document cannot disagree about what the run supports.
    """
    from fastmdxplora.report.document import _assess_this_run

    assessed = _assess_this_run(project_root)
    if not assessed:
        return []

    bullets: list[str] = []
    for record in assessed["observables"].values():
        error = record["standard_error"]
        value = (f"{record['mean']:.4g} ± {error:.3g}" if error is not None
                 else f"{record['mean']:.4g}")
        note = {True: "", False: " (still drifting)",
                None: " (too short to say if equilibrated)"}[record.get("equilibrated", record.get("settled"))]
        bullets.append(
            f"{record['observable']}: {value}"
            f"  [{record['effective_samples']:.0f} independent samples]{note}")

    for finding in (assessed.get("findings") or [])[:3]:
        bullets.append("")
        bullets.append(str(finding))
    return bullets


def _load_analysis_manifest(analysis_dir: Path) -> dict:
    """Read the analysis manifest if present; return {} otherwise."""
    import json

    mf = analysis_dir / "analysis_manifest.json"
    if not mf.exists():
        return {}
    try:
        with mf.open(encoding="utf-8") as fh:
            return json.load(fh)
    except (OSError, json.JSONDecodeError):
        return {}


def build_slides(
    *,
    orchestrator: "FastMDXplora",
    output_dir: Path,
    title: str,
) -> list[str]:
    """Render the slide deck.

    Returns the list of artifact paths (relative to ``output_dir``).
    """
    artifacts: list[str] = []

    # Always write the Markdown outline (no dependencies, always works).
    outline_path = output_dir / "slides_outline.md"
    outline_path.write_text(_outline_markdown(orchestrator, title), encoding="utf-8")
    artifacts.append("slides_outline.md")

    # Try to write a .pptx if python-pptx is available.
    try:
        pptx_path = output_dir / "slides.pptx"
        _build_pptx(orchestrator, title, pptx_path)
        artifacts.append("slides.pptx")
        logger.debug("slides: wrote %s", pptx_path)
    except ImportError:
        logger.debug(
            "slides: python-pptx not importable; wrote markdown outline only. "
            "python-pptx is a core dependency, so this usually means a broken "
            "install — try `pip install --force-reinstall python-pptx`."
        )
    except Exception as exc:  # noqa: BLE001
        logger.warning("slides: pptx generation failed: %s", exc)

    return artifacts
